apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: open-webui
  name: open-webui
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: open-webui
    spec:
      containers:
      - image: ghcr.io/open-webui/open-webui:main
        name: open-webui
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: http://ollama:11434
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: open-webui
  name: open-webui
  namespace: ollama
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: open-webui
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: open-webui
  name: open-webui-lb
  namespace: ollama
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: open-webui
  type: LoadBalancer
status:
  loadBalancer: {}
